### ISSUE TITLE
Must run inside the builder container.  See README.md.

### ISSUE THREAD

**Issue by khanhhoaa19** [openslide/openslide-bin#173]
After pulling images from the command "docker run -ti --rm -v D:/code/testOpenslide/openslide-winbuild-20231011:/work -w /work ghcr.io/openslide/winbuild-builder ./build.sh bdist" I have noticed:
Unable to find image 'ghcr.io/openslide/winbuild-builder:latest' locally
latest: Pulling from openslide/winbuild-builder
acc79bbc8365: Pull complete
66b7f93fd71c: Pull complete
904dff09377b: Pull complete
89172aaa16fa: Pull complete
fde3327ddf3a: Pull complete
37244c8b96f7: Pull complete
5f8fef332f38: Pull complete
e93c8f0a8183: Pull complete
252ceaa2b43d: Pull complete
0b583ddec720: Pull complete
Digest: sha256:29225b9aec5f3b9cd14349731e7e0171516400a5d6ba089534ca9dc7226121f5
Status: Downloaded newer image for ghcr.io/openslide/winbuild-builder:latest
Must run inside the builder container.  See README.md.

How do I run inside the builder container? README.md didn't mention it.

**Comment by bgilbert** [comment]
You are running inside the builder container, but the error message isn't very clear.  `build.sh` checks the compatibility version of the container image, and the check failed.  In this case, it's because you're using a current container image but an old version of openslide-winbuild, and we've just dropped the 32-bit compiler from the container.

If you can't update to the current openslide-winbuild (now called openslide-bin), and you don't plan to build 32-bit images, you can work around this by changing the `/etc/openslide-winbuild-builder-v1` test to check for `-v2` instead.

**Comment by bgilbert** [comment]
Oh, you're building the latest stable release from source.  I... hadn't really anticipated that.  The source is mainly there to fulfill license obligations, so it should indeed build successfully, but I was expecting that folks would mostly use the official binaries.  For future reference, could you explain your use case?

We should probably try to avoid breaking container compatibility with the most recent stable release until the next release is out.  I'm expecting a new release within a few weeks, so hopefully it won't be broken for too long.

Another workaround is to build with a [slightly older container image](https://github.com/openslide/openslide-bin/pkgs/container/winbuild-builder/142028394).

**Comment by khanhhoaa19** [comment]
Yes, I release from source. I pulled the source code and ran the command to build the source, but when I finished, it was noticed like this. I don't know how to explain to you =(

**Comment by khanhhoaa19** [comment]
After building this code, I try to write CMakelists to link the OpenSlide library to my project, which uses the C++ language.

**Comment by bgilbert** [comment]
Okay, thanks.  Of course, it's perfectly fine to build from source if you prefer!

PR to improve the error message: https://github.com/openslide/openslide-bin/pull/174

**Comment by bgilbert** [comment]
[openslide-bin 4.0.0.2](https://github.com/openslide/openslide-bin/releases/tag/v4.0.0.2) is now available.  (We've renamed openslide-winbuild to openslide-bin and restructured the project.)  This release should work correctly with the current versions of the builder containers.  Thanks for your patience, and for reporting this problem!
