### ISSUE TITLE
Building on Windows wrong command line in readme

### ISSUE THREAD

**Issue by nbgeraphl** [openslide/openslide-bin#181]
I tried to build openslide for windows binaries on Windows using WSL (needed) Docker.

64 bit building works fine, 32 bit building leads to the following error:

```
  meson/meson.build:1:0: ERROR: Unknown compiler(s): [['i686-w64-mingw32-gcc']]
  The following exception(s) were encountered:
  Running `i686-w64-mingw32-gcc --version` gave "[Errno 2] No such file or directory: 'i686-w64-mingw32-gcc'"
```

Anyway it is necessary to start docker using Powershell on CMD there are problems with the directory and the command line has to be adjusted a little (see the added braces on `PWD`):

````
docker run -ti --rm -v ${PWD}:/work -w /work ghcr.io/openslide/winbuild-builder ./build.sh -m64 bdist
````
Maybe add this to the readme so others won't run into the same problems.

**Comment by bgilbert** [comment]
We've dropped support for building 32-bit binaries, so the container doesn't have a 32-bit compiler anymore.  If you have an older version of openslide-winbuild, you can still build 32-bit binaries using an [older container image](https://github.com/openslide/openslide-bin/pkgs/container/winbuild-builder/142028394).

Thanks for pointing out the documentation issues!  Fix in https://github.com/openslide/openslide-bin/pull/182.
