### ISSUE TITLE
Use LittleCMS library in openslide Library

### ISSUE THREAD

**Issue by HarshadHapaniWork** [openslide/openslide-bin#196]
I want to use LittleCMS library(https://github.com/mm2/Little-CMS/archive/refs/tags/2.12.tar.gz) in openslide library(openslide.c).

how create lcms2.wrap, How many changes are required in build.sh

**Comment by bgilbert** [comment]
In general, follow the example of other subprojects in this repo.  See the Meson [wrap documentation](https://mesonbuild.com/Wrap-dependency-system-manual.html) for more information about wraps.  Also, be advised that `build.sh` will be completely replaced very soon.

Also note that OpenSlide intentionally does not perform color management itself.  It provides APIs to retrieve the ICC profile of a slide file, and then expects the application to do its own color management.  I'd strongly recommend following that approach instead.
