### ISSUE TITLE
windows 11 using python  import openslide error

### ISSUE THREAD

**Issue by simzhangbest** [openslide/openslide-bin#268]
when I import openslide in python console on windows11 , It report that :
`OpenSlideVersionError: OpenSlide >= 3.4.0 required`

and when I use openslide-show-properties --version in CMD terminal:

```
openslide-show-properties 3.4.1, using OpenSlide 3.4.1
Copyright (C) 2007-2015 Carnegie Mellon University and others

OpenSlide is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License, version 2.1.
<http://gnu.org/licenses/lgpl-2.1.html>

OpenSlide comes with NO WARRANTY, to the extent permitted by law.  See the
GNU Lesser General Public License for more details.
```

and I have write the bin and lib dir to system Path, CMD terminal can use openslide ,but python can't !!! why?
can Any one help?

**Comment by bgilbert** [comment]
I was unable to reproduce this with OpenSlide Python 1.3.1 and the 20230414 OpenSlide binaries.  What versions are you using?  Is there a reason you couldn't use the most recent OpenSlide binary release?

**Comment by bgilbert** [comment]
Closing due to lack of response.  If you're able to supply the requested information, please feel free to comment here.
